# Generated by Django 6.0.3 on 2026-03-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
