# Generated by Django 6.0.3 on 2026-03-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('handyman', 'Handyman'), ('admin', 'Administrator')], default='client', max_length=10),
        ),
    ]
