# Generated by Django 5.2.10 on 2026-05-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_user_wallet_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wallet_locked_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
