# Generated by Django 6.0.3 on 2026-03-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
