# Generated by Django 5.2.10 on 2026-03-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_alter_booking_scheduled_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="client_proposed_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="handyman_proposed_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="negotiation_status",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("awaiting_handyman", "Awaiting Handyman"),
                    ("awaiting_client", "Awaiting Client"),
                    ("agreed", "Agreed"),
                    ("declined", "Declined"),
                ],
                default="none",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
