# Generated by Django 5.2.10 on 2026-03-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_booking_client_proposed_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="handyman_counter_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
