# Generated by Django 6.0.3 on 2026-03-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_client_counter_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration_hours',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
