# Generated by Django 6.0.3 on 2026-03-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_duration_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='duration_hours',
        ),
        migrations.AddField(
            model_name='booking',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
