# Generated by Django 6.0.3 on 2026-03-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_booking_duration_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
