# Generated by Django 6.0.3 on 2026-04-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_created_at_booking_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
