# Generated by Django 6.0.3 on 2026-04-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_is_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='last_action_by',
            field=models.CharField(choices=[('client', 'Client'), ('handyman', 'Handyman')], default='client', max_length=10),
        ),
    ]
