# Generated by Django 6.0.3 on 2026-04-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_last_action_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='knows_fix',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
