# Generated by Django 6.0.3 on 2026-04-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_knows_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='handyman_marked_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
