# Generated by Django 5.2.10 on 2026-05-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0020_booking_continue_job_confirmed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrowhold",
            name="purpose",
            field=models.CharField(
                choices=[("visit_fee", "Visit Fee"), ("quote", "Quote")],
                default="quote",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="proposed_visit_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
