# Generated by Django 5.2.10 on 2026-06-03 20:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0022_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrowhold",
            name="app_fee_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="escrowhold",
            name="handyman_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="escrowhold",
            name="pdv_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
