# Generated by Django 5.2.12 on 2026-06-05 10:34

import bookings.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_bookingattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingattachment',
            name='file',
            field=models.FileField(storage=bookings.storage.BookingAttachmentStorage(), upload_to='%Y/%m/'),
        ),
    ]
